### ISSUE TITLE
Hi,When I run hddldaemon and BurnInTest in the same time for a stress test,hddldaemon reported an error

### ISSUE THREAD

**Issue by BIOSkisuki** [IntelAI/OpenVINO-model-server#118]
When I run hddldaemon and BurnInTest in the same time for a stress test,hddldaemon reported an error and lost Device.Do you have any suggest for this issue?
![image](https://user-images.githubusercontent.com/54833942/70291920-9321c600-1817-11ea-9651-4206e0de3108.png)

**Comment by mzegla** [comment]
Looks like issue related to HDDL rather then model server itself. I'm afraid I won't be able to help you nor reproduce this issue. You can try to get help on OpenVINO forum:
https://software.intel.com/en-us/forums/computer-vision.

**Comment by subashp** [comment]
Hey @BIOSkisuki, what is BurnInTest and how can I recreate your issue at my end?

**Comment by subashp** [comment]
@mzegla since there is no response, should we close this issue?
