### ISSUE TITLE
Is it possible to run with --target GPU

### ISSUE THREAD

**Issue by dcflachs** [IntelAI/OpenVINO-model-server#126]
Does anyone know if it is possible to build the docker version of this with support for acceleration via intel GPUs?

**Comment by mzegla** [comment]
Hi, 
We didn't test model server with GPU, but looking at binary Dockerfile, you can try it by adding
**ocl-icd-opencl-dev** package installation after **wget** in 
https://github.com/IntelAI/OpenVINO-model-server/blob/master/Dockerfile_binary_openvino#L22
and then build your image. Then specify _---target_device_ **GPU** while starting model server.
Unfortunately I don't have access to GPU right now to confirm it.

**Comment by dcflachs** [comment]
Unfortunately I get this error after building the Docker with the  ocl-icd-opencl-dev package and attempting to specify --target_device GPU.
`ie_serving.models.model - ERROR - Content error: Cannot find plugin to use :Tried load plugin : clDNNPlugin,  error: Plugin clDNNPlugin cannot be loaded: cannot load plugin: clDNNPlugin from : clGetPlatformIDs error -1001, skipping
cannot load plugin: clDNNPlugin from /opt/intel/openvino_2019.3.376/python/python3.5/openvino/inference_engine: Cannot load library '/opt/intel/openvino_2019.3.376/python/python3.5/openvino/inference_engine/libclDNNPlugin.so': /opt/intel/openvino_2019.3.376/python/python3.5/openvino/inference_engine/libclDNNPlugin.so: cannot open shared object file: No such file or directory, skipping
`
Note my docker run command does contain  `--privileged --device /dev/dri`

**Comment by dcflachs** [comment]
I was eventually able to get this to work, using a combination of the suggestion above and the info available [here](https://docs.openvinotoolkit.org/2018_R5/_docs_install_guides_installing_openvino_docker.html). As for the error i posted above, that appears to be the result of attempting to run the container on non-supported hardware. Specifically i believe that GPU requires a 6th gen or newer Intel Core processor.
