### ISSUE TITLE
make docker_build_clearlinux fails to build

### ISSUE THREAD

**Issue by jiria** [IntelAI/OpenVINO-model-server#127]
I am trying to rebuild the container image using: `make docker_build_clearlinux` and it fails with:

```
Step 6/9 : RUN pip --no-cache-dir install -r requirements_clearlinux.txt
 ---> Running in 6f46c85b84ae
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0 (from -r requirements_clearlinux.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for tensorflow==1.14.0 (from -r requirements_clearlinux.txt (line 1))
The command '/bin/sh -c pip --no-cache-dir install -r requirements_clearlinux.txt' returned a non-zero code: 1
Makefile:113: recipe for target 'docker_build_clearlinux' failed
```

**Comment by jiria** [comment]
Just to add, `make docker_build_apt_ubuntu` builds fine.

**Comment by mzegla** [comment]
Clearlinux in it's latest versions switched to Tensorflow 2.0 and Python 3.8, that's why you see these errors. We plan to enable TF 2.0 and Python 3.8 for our next release.

**Comment by jiria** [comment]
Thanks. Curious, is there an ETA for the next release? Having said that, I would be fine with any image, Clearlinux or Ubuntu for now.

**Comment by mzegla** [comment]
Some time in February I believe. We're waiting for the next public OpenVINO release to come first, so we can align to it in model server release.

**Comment by dtrawins** [comment]
clearlinux image is fixed now on master branch so I'm closing this issue
