### ISSUE TITLE
Model Server Hangs with --target_device=MYRIAD

### ISSUE THREAD

**Issue by dcflachs** [IntelAI/OpenVINO-model-server#144]
So this issue is similar to other posted involving NCS2 devices and the Myriad plugin in docker, but i think the specifics here may be unique. After many attempts i was finally able to build an image based on [this](https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_docker_linux.html) guide, your Dockerfile_binary_openvino and the Open Vino Workbench dockerfile in which i could access my NCS2 device. I can confirm access to the MYRIAD device by using the `demo_squeezenet_download_convert_run.sh` script from the openvino installation with a MYRIAD target. however when i attempt to launch the model server, whether or not I have run the demo script within the container, it always hangs without completely starting up. If set the LOG_LEVEL=DEBUG the last line printed before it hangs is 
` ie_serving.models.ir_engine - DEBUG - [Model: model_1, version: 3] --- effective batch size - auto`
I have tried with batch size set to 1, with the same result. Additionally if i set the target device to CPU the model server start up normally. At this point I am once again stuck, any help would be appreciated.
<details>
  <summary>My Dockerfile</summary>
  
```
FROM ubuntu:18.04
USER root
WORKDIR /

RUN useradd -ms /bin/bash openvino && \
    chown openvino -R /home/openvino

ARG INSTALLDIR=/opt/intel/openvino
ARG TEMP_DIR=/tmp/openvino_installer
ARG DL_INSTALL_DIR="$INSTALLDIR/deployment_tools"

ARG DEPENDENCIES="autoconf \
                  automake \
                  build-essential \
                  cmake \
                  cpio \
                  curl \
                  gnupg2 \
                  libdrm2 \
                  libglib2.0-0 \
                  lsb-release \
                  libgtk-3-0 \
                  libtool \
#                  python3-pip \
                  udev \
                  unzip"

ARG OTHER_DEPENDENCIES="virtualenv  \
			sudo \
			python3.5-dev \
                       "

RUN apt-get update && \
    apt-get install -y --no-install-recommends software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends ${DEPENDENCIES} ${OTHER_DEPENDENCIES} && \
    rm -rf /var/lib/apt/lists/*

ADD l_openvino_toolkit*.tgz $TEMP_DIR/

RUN cd $TEMP_DIR/l_openvino_toolkit* && \
    sed -i 's/decline/accept/g' silent.cfg && \
    ./install.sh -s silent.cfg --ignore-signature && \
    rm -Rf $TEMP_DIR

#FOR VPU
RUN usermod -aG users openvino
RUN cp ${INSTALLDIR}/deployment_tools/inference_engine/external/97-myriad-usbboot.rules /etc/udev/rules.d/ && \
    ldconfig

WORKDIR /opt
RUN curl -L https://github.com/libusb/libusb/archive/v1.0.22.zip --output v1.0.22.zip && \
    unzip v1.0.22.zip && cd libusb-1.0.22 && \
    ./bootstrap.sh && \
    ./configure --disable-udev --enable-shared && \
    make -j4

RUN apt-get update && \
    apt-get install -y --no-install-recommends libusb-1.0-0-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/libusb-1.0.22/libusb
RUN /bin/mkdir -p '/usr/local/lib' && \
    /bin/bash ../libtool   --mode=install /usr/bin/install -c   libusb-1.0.la '/usr/local/lib' && \
    /bin/mkdir -p '/usr/local/include/libusb-1.0' && \
    /usr/bin/install -c -m 644 libusb.h '/usr/local/include/libusb-1.0' && \
    /bin/mkdir -p '/usr/local/lib/pkgconfig' && \
    cd  /opt/libusb-1.0.22/ && \
    /usr/bin/install -c -m 644 libusb-1.0.pc '/usr/local/lib/pkgconfig' && \
    ldconfig

ENV HDDL_INSTALL_DIR="$DL_INSTALL_DIR/inference_engine/external/hddl"
ENV PYTHONPATH="$INSTALLDIR/python/python3.5"
ENV LD_LIBRARY_PATH="$DL_INSTALL_DIR/inference_engine/external/tbb/lib:$DL_INSTALL_DIR/inference_engine/external/mkltiny_lnx/lib:$DL_INSTALL_DIR/inference_engine/external/hddl/lib:$DL_INSTALL_DIR/inference_engine/lib/intel64"

WORKDIR /ie-serving-py

COPY start_server.sh setup.py version requirements.txt /ie-serving-py/
RUN virtualenv -p python3.5 .venv && . .venv/bin/activate && pip3 install -r requirements.txt

COPY ie_serving /ie-serving-py/ie_serving

RUN . .venv/bin/activate && pip3 install .
```
</details>

**Comment by kromanow94** [comment]
I was assigned to look into your issue. I'll present my findings as soon as I'll find anything.
Live long and prosper :vulcan_salute:

**Comment by dcflachs** [comment]
Thanks @kromanow94,
One further piece of information that would be useful, i am building the docker image with the `l_openvino_toolkit_p_2019.3.376.tgz` toolkit.

**Comment by kromanow94** [comment]
So I have built the docker images with your Dockerfile and your version of openvino_toolkit and I successfully run the server with docker.

My command:
```bash
docker run -ti --rm --privileged \
    -v /dev:/dev \
    -v /opt/models:/opt/models \
    --network host \
    -e LOG_LEVEL=DEBUG \
    ie-serving-py:myriad2019  \
    /ie-serving-py/start_server.sh ie_serving \
    model  \
    --target_device MYRIAD \
    --model_path /opt/models \
    --model_name mymodel
```

Mind the required mount for `/dev` - it's needed even if you're using `--privileged`.

I have some further questions that may be somewhat relevant:
1. What is the exact command you use to run the ie-serving?
2. What is your model size? Maybe it's too big for the compute stick. Model I used had maximum size of 98MB.
3. Are you sure your compute sticks are working fine?

You can also send the logs here so we have even deeper insight.

**Comment by dcflachs** [comment]
My docker command is as follows,

```
docker run -d --name Intel-Serving-VPU --privileged \
--network="Custom Bridge" \
-v /dev/bus/usb:/dev/bus/usb  \
-v /dev/dri:/dev/dri \
-v /home/dave/run_1-1-1700000-intel:/opt/ml \
-l traefik.enable=true \
-l traefik.http.middlewares.intel-serving-prefix.stripPrefix.prefixes=/intel \
-l traefik.http.routers.intel-serving.entrypoints=intel \
-l traefik.http.routers.intel-serving.middlewares=intel-serving-prefix \
-l traefik.http.routers.intel-serving.rule='PathPrefix(`/intel/`)' \
-l traefik.http.services.intel-serving.loadbalancer.server.port=8502 \
ie-serving-py:latest /ie-serving-py/start_server.sh ie_serving model \
--model_path /opt/ml/ \
--model_name model_1 \
--rest_port 8502 \
--batch_size auto \
--nireq 4 \
--rest_workers=8 \
--target_device MYRIAD
```

I have also used the following docker run command to attached to enter the container where i can navigate to the `/opt/intel/openvino/deployment_tools/demo/` directory and run the demo_squeezenet_download_convert_run.sh with -D MYRIAD which leads me to believe that the device is working correctly within the container.

```
docker run -it --name Intel-Serving-VPU --privileged \
--network="Custom Bridge" \
-v /dev/bus/usb:/dev/bus/usb  \
-v /dev/dri:/dev/dri \
-v /home/dave/run_1-1-1700000-intel:/opt/ml \
-l traefik.enable=true \
-l traefik.http.middlewares.intel-serving-prefix.stripPrefix.prefixes=/intel \
-l traefik.http.routers.intel-serving.entrypoints=intel \
-l traefik.http.routers.intel-serving.middlewares=intel-serving-prefix \
-l traefik.http.routers.intel-serving.rule='PathPrefix(`/intel/`)' \
-l traefik.http.services.intel-serving.loadbalancer.server.port=8502 \
ie-serving-py:latest /bin/bash
```

I hadnt considered the size of the model I will have to check on that, my assumption was that i would get a distinct error from the model server if a model wouldnt fit.

**Comment by kromanow94** [comment]
This is my command that worked with your parameters:
```bash
docker run \
    -d \
    --name Intel-Serving-VPU \
    --privileged \
    --network=host \
    -v /dev/bus/usb:/dev/bus/usb \
    -v /dev/dri:/dev/dri \
    -v /opt/models:/opt/ml \
    -l traefik.enable=true \
    -l traefik.http.middlewares.intel-serving-prefix.stripPrefix.prefixes=/intel \
    -l traefik.http.routers.intel-serving.entrypoints=intel \
    -l traefik.http.routers.intel-serving.middlewares=intel-serving-prefix \
    -l traefik.http.routers.intel-serving.rule='PathPrefix(`/intel/`)' \
    -l traefik.http.services.intel-serving.loadbalancer.server.port=8502 \
    ie-serving-py:myriad2019 /ie-serving-py/start_server.sh ie_serving model \
    --model_path /opt/ml/ \
    --model_name model_1 \
    --rest_port 8502 \
    --batch_size auto \
    --nireq 4 \
    --rest_workers=8 \
    --target_device MYRIAD
```

Versions:
* OpenVino: l_openvino_toolkit_p_2019.3.376.tgz
* OVMS: 2019_R2 (commit d197684 from master branch)
* Model: Resnet v1 50

About the model:
* One might think that checking model size is complicated. Actually it's just `ls -lh`.
* Can you send us some information about your model? It's size, where did you get it from... If you can it would be best if you can send us your model.

Also, can you check if `--network host` parameter helps you? Although that would be very weird if it helps but just to make sure we've tried everything...

**Comment by dcflachs** [comment]
@kromanow94 Thanks for your help.

It appears that you were correct that the model i was trying to use was to big, 114MB. I tried as smaller model, a Resnet 101 91MB, and was able to get things to work just fine. I did not need to try `--network host`.

**Comment by brmarkus** [comment]
Is it documented what the max size of model could be on a Myriad-X NCS2...?

**Comment by esmirno** [comment]
@brmarkus max size of ma2480 soc_rev supposed to be near 512MB. So model size itself least likely to be a root cause. As i remember correctly NCS-2 stick can simultaneously infer 3 alexnets, which is about 120Mb each.
