### ISSUE TITLE
gs://intelai_public_models not found

### ISSUE THREAD

**Issue by cliveseldon** [IntelAI/OpenVINO-model-server#149]
```
gsutil ls gs://intelai_public_models
BucketNotFoundException: 404 gs://intelai_public_models bucket does not exist.
```

We were using the above for some examples in Seldon Core. Is there a new location?

**Comment by dtrawins** [comment]
New location is gs://public-artifacts/intelai_public_models/ 
I just filed a PR for seldon core https://github.com/SeldonIO/seldon-core/pull/1492
