### ISSUE TITLE
error Inputs expected to be in the set {['0']}

### ISSUE THREAD

**Issue by aikudexiaohai** [IntelAI/OpenVINO-model-server#27]
I start a  server with person-attributes-recognition-crossroad model，and I send a image use gprc， but I got 
status = StatusCode.INVALID_ARGUMENT
details = "input tensor alias not found in signature: ['inputs']. Inputs expected to be in the set{['0']}."

this is my client:
image = cv2.imread('1.png')
image = image.transpose(2,0,1)
image = np.expand_dims(image, 1)

request.inputs['inputs'].CopyFrom(tf.contrib.util.make_tensor_proto(image, shape=(image.shape)))

this is info after start a server：
ie_serving.models.ir_engine - INFO - Matched keys for model: {'inputs': {'0': '0'}, 'outputs': {'453': '453', '455': '455', '457': '457'}}

the server means he need a dict format image，so how should I send my image

**Comment by dtrawins** [comment]
Based on the included logs I think there is some problem with the OpenVINO model configuration.
It looks like in your model the input tensor is called '0' and the outputs names are '453', '455' and '457'.
You need to adjust the model optimizer command.
In the grpc client the input and output names should match those defined in the model and the server. The example grpc client has parameters --input_name and --output_name.
