### ISSUE TITLE
`docker build .` fails 

### ISSUE THREAD

**Issue by ryanloney** [IntelAI/OpenVINO-model-server#41]
Here is where it gets stuck: 
```
Step 18/25 : COPY start_server.sh setup.py requirements.txt version /ie-serving-py/
COPY failed: stat /var/lib/docker/tmp/docker-builder606115979/version: no such file or directory
```

In order to get `docker build .` to run, I need to remove `version` from line 65 
```
COPY start_server.sh setup.py requirements.txt version /ie-serving-py/
```
Is this supposed to be here? 

Thanks, 

Ryan

**Comment by dtrawins** [comment]
version file is generated by the Makefile. You should build the docker using command:
`make docker_build_src_ubuntu http_proxy=$http_proxy https_proxy=$https_proxy`
or
`make docker_build_src_intelpython http_proxy=$http_proxy https_proxy=$https_proxy`
or
`make docker_build_bin http_proxy=$http_proxy https_proxy=$https_proxy`
The last command requires a binary package of OpenVINO.

You might also drop the version file in the dockerfile. This file is used only to track the version info for the support purposes. We might consider changing it in the future.

**Comment by ryanloney** [comment]
That worked! Thank you @dtrawins.
