### ISSUE TITLE
Can I use it under Windows?

### ISSUE THREAD

**Issue by qindj** [IntelAI/OpenVINO-model-server#5]
Hi ,Admin

How can i use this model server under windows without docker?

thx

**Comment by dtrawins** [comment]
Actually Windows was not anticipated as the hosting OS. I would expect in few places problems related to the path format. Potentially in cygwin the server could be started successfully but it was not tested. For now there are no plans to add official support for Windows OS.
If you are willing to try it on your own there should be installed OpenVINO package in the first place and the same python dependencies installed like described in the Dockerfile.

**Comment by qindj** [comment]
thanks very much , I'll have a try on Windows & report here soon
