### ISSUE TITLE
gRPC client examples fails

### ISSUE THREAD

**Issue by ramakrishnapallala** [IntelAI/OpenVINO-model-server#50]
Build steps Pass:
cp (download path)/l_openvino_toolkit_p_2019.1.094_online.tgz . 
make docker_build_bin http_proxy=$http_proxy https_proxy=$https_proxy

Placed ResNet-50 model under /opt/ml/model1/1 folder

Starting Docker Container with a Single Model with:
docker run --rm -d  -v /models/:/opt/ml:ro -p 9001:9001 ie-serving-py:latest \
/ie-serving-py/start_server.sh ie_serving model --model_path /opt/ml/model1 --model_name my_model --port 9001

The following command is failing with below log:
python grpc_serving_client.py --grpc_port 9001 --images_numpy_path imgs.npy --input_name data --output_name prob --transpose_input False --labels_numpy lbs.npy

Log:
E0604 18:41:13.744116590   24051 http_proxy.cc:62]           'https' scheme not supported in proxy URI
('Image data range:', 0.0, ':', 255.0)
Start processing:
        Model name: resnet
        Iterations: 10
        Images numpy path: imgs.npy
        Images in shape: (10, 3, 224, 224)

Traceback (most recent call last):
  File "grpc_serving_client.py", line 105, in <module>
    result = stub.Predict(request, 10.0) # result includes a dictionary with all model outputs
  File "/usr/lib64/python2.7/site-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/lib64/python2.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.NOT_FOUND
        details = "Servable not found for request: Specific(resnet, 0)"
        debug_error_string = "{"created":"@1559653873.758416316","description":"Error received from peer ipv6:[::1]:9001","file":"src/core/lib/surface/call.cc","file_line":1046,"grpc_message":"Servable not found for request: Specific(resnet, 0)","grpc_status":5}"
>

@dtrawins How can I fix this issue? is it a known issue?

**Comment by ramakrishnapallala** [comment]
same issue:
https://stackoverflow.com/questions/55674762/openvino-serving-servable-not-found-for-request

**Comment by dtrawins** [comment]
@ramakrishnapallala Looking at your description I think you should place the model files in /models/model1/1 folder. You might confirm if the service is started successfully by checking the docker container logs. 

Other thing to confirm is the proxy settings. While you are connecting to the localhost interface, make sure you don't have configured http_proxy env or you have localhost included in no_proxy.

**Comment by ramakrishnapallala** [comment]
> @ramakrishnapallala Looking at your description I think you should place the model files in /models/model1/1 folder. You might confirm if the service is started successfully by checking the docker container logs.
> 
> Other thing to confirm is the proxy settings. While you are connecting to the localhost interface, make sure you don't have configured http_proxy env or you have localhost included in no_proxy.

My model is placed under /opt/ml/model1/1/ and the service is started successfully.

docker run --rm -d  -v /models/:/opt/ml:ro -p 9001:9001  --env LOG_LEVEL=DEBUG --env LOG_PATH=/var/log/ie_serving.log  ie-serving-py:latest /ie-serving-py/start_server.sh ie_serving model --model_path /opt/ml/model1 --model_name resnet --port 9001

2019-06-05 14:21:49,464 - ie_serving.models.model - DEBUG - []
2019-06-05 14:21:50,466 - ie_serving.models.model - DEBUG - []
2019-06-05 14:21:51,467 - ie_serving.models.model - DEBUG - []
2019-06-05 14:21:52,469 - ie_serving.models.model - DEBUG - []
2019-06-05 14:21:53,471 - ie_serving.models.model - DEBUG - []

after running the inference request i get the following log from service.

**python grpc_serving_client.py --grpc_port 9001 --images_numpy_path imgs.npy --input_name data --output_name prob --transpose_input False --labels_numpy lbs.npy**

python grpc_serving_client.py --grpc_port 9001 --images_numpy_path imgs.npy --input_name data --output_name prob --transpose_input False --labels_numpy lbs.npy
E0605 19:56:41.488049049    3815 http_proxy.cc:62]           'https' scheme not supported in proxy URI
('Image data range:', 0.0, ':', 255.0)
Start processing:
        Model name: resnet
        Iterations: 10
        Images numpy path: imgs.npy
        Images in shape: (10, 3, 224, 224)

Traceback (most recent call last):
  File "grpc_serving_client.py", line 105, in <module>
    result = stub.Predict(request, 10.0) # result includes a dictionary with all model outputs
  File "/usr/lib64/python2.7/site-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/lib64/python2.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.NOT_FOUND
        details = "Servable not found for request: Specific(resnet, 0)"
        debug_error_string = "{"created":"@1559744801.502814900","description":"Error received from peer ipv6:[::1]:9001","file":"src/core/lib/surface/call.cc","file_line":1046,"grpc_message":"Servable not found for request: Specific(resnet, 0)","grpc_status":5}"

**sudo docker logs dreamy_ramanujan**

2019-06-05 14:23:34,626 - ie_serving.models.model - DEBUG - []
2019-06-05 14:23:35,628 - ie_serving.models.model - DEBUG - []
**2019-06-05 14:23:35,772 - ie_serving.server.service - DEBUG - PREDICT, invalid model spec from request, resnet - 0**
2019-06-05 14:23:36,630 - ie_serving.models.model - DEBUG - []

**Comment by dtrawins** [comment]
@ramakrishnapallala you service doesn't seem to start correctly. The container is running but it is waiting the for models to be present in the requested path in the container `/opt/ml/model1`. 
If you have the model files on the host in `/opt/ml/model1/1/` you should start the container with different parameters:
`docker run --rm -d -v /opt/ml:/opt/ml:ro -p 9001:9001 --env LOG_LEVEL=DEBUG --env LOG_PATH=/var/log/ie_serving.log ie-serving-py:latest /ie-serving-py/start_server.sh ie_serving model --model_path /opt/ml/model1 --model_name resnet --port 9001`
The parameter `-v` maps the path on the host with the path in the container.

**Comment by ramakrishnapallala** [comment]
Thank you @dtrawins, now it works.
