### ISSUE TITLE
Can't start docker container with NCS

### ISSUE THREAD

**Issue by openedhardware** [IntelAI/OpenVINO-model-server#51]
> Plugin for Intel® Movidius™ Neural Compute Stick is distributed only in a binary form, so loading models on NCS is possible only with binary built docker image.

What does this mean?
So can't I use your built-in docker image?

I tried with `ssd_inception_v2` model and got this error:
![image](https://user-images.githubusercontent.com/16890683/59248156-2fe21d00-8c54-11e9-811a-2d151a568ad4.png)

I was able to inference the model using this sample code directly:
https://gist.github.com/kodamap/9a9c971f43bffdc457a628c4313947fe

Any idea?

**Comment by mzegla** [comment]
Hi, docker image available on docker hub does not support NCS. 
To have docker image that supports NCS you need to build it yourself following steps in:
https://github.com/IntelAI/OpenVINO-model-server/blob/master/docs/docker_container.md#building-the-image.

First you need to get openvino toolkit for linux (tgz file). You can register and download it from 
https://software.intel.com/en-us/openvino-toolkit/choose-download. 
Then place downloaded tgz file under root of OpenVINO-model-server and use make to build OVMS docker image that supports NCS:

```
cp (download path)/l_openvino_toolkit_p_2019.x.xxx.tgz .
make docker_build_bin http_proxy=$http_proxy https_proxy=$https_proxy
```

**Comment by openedhardware** [comment]
@mzegla 
Thanks for your quick reply!

Is there anything I can configure to enable NCS before building OVMS docker image?

Or, just follow your instruction above?

**Comment by mzegla** [comment]
Hmm, after you build your image make sure your NCS is available on host machine.
https://github.com/IntelAI/OpenVINO-model-server/blob/master/docs/docker_container.md#starting-docker-container-with-ncs
Also check out **Updating udev rules**, you might need it.
Once you've done it and got docker image built you can try running it. 
Let me know how did it work 😄

**Comment by openedhardware** [comment]
I will give it a try tomorrow morning early.
Thanks!
