### ISSUE TITLE
Should I install OpenVINO first?

### ISSUE THREAD

**Issue by qindj** [IntelAI/OpenVINO-model-server#6]
or I only need to deploy OpenVINO optimized model?

thx

**Comment by dtrawins** [comment]
OpenVINO toolkit installation is a mandatory component before OpenVINO model server installation.
You can refer to the documentation on https://github.com/IntelAI/OpenVINO-model-server/blob/master/docs/host.md 
Similar steps should be followed to those listed in Dockerfile or Dockerfile_binary_openvino

**Comment by dtrawins** [comment]
you can try 2 options:
- binary distribution of OpenVINO toolkit from https://software.intel.com/en-us/openvino-toolkit/choose-download/free-download-windows
- build inference engine from sources according to the readme from https://github.com/opencv/dldt/tree/2018/inference-engine#build-on-windows-systems
You could use VS2017 or cmake. VS community version should be sufficient. 
In both cases you could select components to install. Dependencies required for the OV Model Server are included in the dockerfiles (separately for docker building from sources and from the binary package).

**Comment by qindj** [comment]
You saved my life! Enjoy your weekend!
