### ISSUE TITLE
Support for intel Atom based processor(non AVX instruction set)

### ISSUE THREAD

**Issue by golisandeep3** [IntelAI/OpenVINO-model-server#84]
Currently the model server fails to run on hardware which doesn't contain AVX instructions.

tensorflow==1.13.1  --> This build is compiled on AVX instructions. 
 
**Error**
2019-07-18 21:30:52.201867: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
/models/inference_engine_entrypoint.sh: line 25:   148 Aborted                 (core dumped) /ie-serving-py/start_server.sh ie_serving config --config_path /models/models.conf --port 8500 --rest-port 8501

**Comment by dtrawins** [comment]
@golisandeep3 Could you validate if the same solution from https://github.com/IntelAI/OpenVINO-model-server/issues/49 could work for you?

**Comment by golisandeep3** [comment]
@dtrawins  It doesn't work.  ERROR: tf_nightly-1.13.1-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by golisandeep3** [comment]
@dtrawins It is built for python3.6.I see the model server uses python 3.5 . I found one for python 3.5 and tensorflow 1.12.0 .I got it working with this package http://data.neural.cz/tensorflow-wheels/cpu-no-avx-sse4/tensorflow-1.12.0-cp35-cp35m-linux_x86_64.whl. Does model server have hard requirement  for tensorflow 1.13.0 version ? do we face any issues with 1.12.0 version ?

**Comment by dtrawins** [comment]
Tensorflow 1.12.0 will also work fine with OVMS. Both python 3.5 and 3.6 can be used.
