### ISSUE TITLE
Unexpected results when processing batches with face-detection-retail-0004

### ISSUE THREAD

**Issue by Steedance** [IntelAI/OpenVINO-model-server#86]
I already have a working solution with the model by processing input data with the shape (1, 3, 300, 300) multiple times, but I am looking to increase the performance of my solution using batch processing.

My issue is as follows:
If I, for example, process an input with the shape (4, 3, 300, 300) it seems like only the first of the batch returns correct values. The others will return confidence, image_id and label values (that look potentially correct) and a 0 as each of the other values (xmin, xmax, ymin, ymax).
Below is an example of part of the output.

`[1.0, 1.0, 0.999951243401, 0.0, 0.0, 0.0, 0.0] , 
[1.0, 1.0, 0.99983048439, 0.0, 0.0, 0.0, 0.0] , 
[1.0, 1.0, 0.999551355839, 0.0, 0.0, 0.0, 0.0] , 
[1.0, 1.0, 0.998133003712, 0.0, 0.0, 0.0, 0.0] , 
[1.0, 1.0, 0.998106598854, 0.0, 0.0, 0.0, 0.0] , 
[1.0, 1.0, 0.966695904732, 0.0, 0.0, 0.0, 0.0] , 
[1.0, 1.0, 0.948006510735, 0.0, 0.0, 0.0, 0.0] , 
[1.0, 1.0, 0.897149503231, 0.0, 0.0, 0.0, 0.0] , 
[1.0, 1.0, 0.670906364918, 0.0, 0.0, 0.0, 0.0] , 
[1.0, 1.0, 0.59589445591, 0.0, 0.0, 0.0, 0.0] ,`

I have used batch processing for other models and it has worked as expected but I'm not sure what is happening with face-detection-retail-0004.

Any help would be appreciated.

**Comment by dtrawins** [comment]
@Steedance Do you use REST or gRPC interface in your calls? In case of REST do you use row and column format of the [input json](https://www.tensorflow.org/tfx/serving/api_rest)?  Could you validate the output shape using GetModelMetadata function? Perhaps that will reveal what should be expected in the inference results.
Have you increase the model batch size by adding the `-batch_size 4` parameter in OVMS startup command?

**Comment by Steedance** [comment]
@dtrawins 
Thanks for the fast response.

I'm using gRPC for my calls. The output shape returned by the GetModelMetadata function is [1L, 1L, 200L, 7L] as expected and when I send input data with a shape (4, 3, 300, 300) the response has a shape (4, 1, 200, 7). From what I have done with other models this seems to be correct.

I hadn't tried adding the `-batch_size` command as I am loading multiple models onto the server via config.json and I have set the batch size for all the models to auto. I just tested this and I get the same response. The first response in the batch is correct and the other 3 follow the format [id, label, conf, 0, 0, 0, 0].

Is this reproducible for you or does this model work as expected when you use it?

Thanks

**Comment by Steedance** [comment]
I still haven't resolved this, any help would be appreciated.

**Comment by mzegla** [comment]
Hi, 

I've managed to reproduce your issue. I run inference on this model both via model server and directly with OpenVINO toolkit and got the same results, so I wouldn't say it's a model server issue. We're in touch with OpenVINO team and will investigate this issue. 

Sorry for the inconvenience.

**Comment by mzegla** [comment]
Alright, so for the kind of model you use, batching is done in a different way, that is not currently supported in OVMS.  Inference on different batch size in your case can be done with input layer reshaping. We plan to add support for that in next model server release.

**Comment by dtrawins** [comment]
@Steedance we are developing a solution to the issue you raised in this PR https://github.com/IntelAI/OpenVINO-model-server/pull/97 
You will be able to use --shape option which will let you change the batch size for object detection models and even change the image size as well.
You might give it a try now.

**Comment by mzegla** [comment]
Fixed in https://github.com/IntelAI/OpenVINO-model-server/releases/tag/v2019.2
Check out: 
https://github.com/IntelAI/OpenVINO-model-server/blob/master/docs/docker_container.md#model-reshaping
For this case you can set shape parameter for your model to: 
* (4,3,300,300) - to set fixed batch size to 4 
* auto - for dynamic reshaping (simply send data in desired shape and OVMS will reshape your model to work with your input data)
