### ISSUE TITLE
how to get libcpu_extension_avx2.so?

### ISSUE THREAD

**Issue by alwan1989** [IntelAI/OpenVINO-model-server#93]
plugin = IEPlugin(device=args.device, plugin_dirs=args.plugin_dir)
    if args.cpu_extension and 'CPU' in args.device:
        plugin.add_cpu_extension(args.cpu_extension)
------------------------------------------------------------------------
and parser.add_argument("-l", "--cpu_extension",
                        help="MKLDNN (CPU)-targeted custom layers.Absolute path to a shared library with the kernels "
                             "impl.", type=str, default='C:\Users\HHH\Documents\Intel\OpenVINO\inference_engine_samples_build\intel64\Release')
i can't find libcpu_extension_avx2.so file.
C:\Users\HHH\Documents\Intel\OpenVINO\inference_engine_samples_build\intel64\Release?

**Comment by mzegla** [comment]
CPU extensions shall be present in your OpenVINO directory. In my case, on Linux I have them under:
`<openvino_toolkit_path>/inference_engine/lib/intel64`

**Comment by dtrawins** [comment]
Closing this issue. To add mode in version 2020.1, cpu extension are included in the CPU plugin. Only custom layers can be optionally added to cpu extensions.

**Comment by gittripley** [comment]
> Closing this issue. To add mode in version 2020.1, cpu extension are included in the CPU plugin. Only custom layers can be optionally added to cpu extensions.

@dtrawins I am newbie here.
Is API changed? I saw IEPlugin("CPU").add_cpu_extension("libcpu_extension.so") still exists in 2020.1 version. But the question is where could I get `libcpu_extension.so`? It no longer exists in 2020 release installation directory.

**Comment by naserpiltan** [comment]
@gittripley  i have same problem.did you solve it ? where is libcpu_sxtension.so in 2020.1 version?

**Comment by brmarkus** [comment]
@gittripley can you provide details about where in 2020.1 you still see "`IEPlugin("CPU").add_cpu_extension("libcpu_extension.so")`"? That would be a bug - as starting with 2020.1 there is no `libcpu_extension.so` anylonger; only custom-layers would need to be loaded as custom-extensions.

@naserpiltan With 2020.1 and newer you don't need to load the `libcpu_extension.so` anylonger - except you have custom-layers to be added.
